#!/usr/bin/env bash
#
# self-demo.sh — run readme2demo on its own repo and wire the results back in.
#
# This is the "recursive demo": readme2demo reads THIS repo, follows
# docs/step-by-step.md, verifies every step in a fresh container, renders a VHS
# video, and publishes the docs. This script then drops the outputs where the
# README and examples gallery expect them.
#
# Requirements (same as any real run — see README "Requirements"):
#   - Docker (running daemon)
#   - VHS + ffmpeg (video render)          https://github.com/charmbracelet/vhs
#   - A model credential, one of:
#       ANTHROPIC_API_KEY          (production; --llm-backend auto -> api)
#       CLAUDE_CODE_OAUTH_TOKEN    (dev; pair with R2D_BACKEND=claude-cli)
#
# Usage:
#   ./scripts/self-demo.sh                 # backend auto (needs ANTHROPIC_API_KEY)
#   R2D_BACKEND=claude-cli ./scripts/self-demo.sh   # dev mode on your subscription
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SELF_URL="https://github.com/alphacrack/readme2demo"
BACKEND="${R2D_BACKEND:-auto}"
BASE_IMAGE="readme2demo/base:latest"

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# --- preflight ---------------------------------------------------------------
say "Preflight"
command -v readme2demo >/dev/null 2>&1 || die "readme2demo not installed. Run: pip install -e \".[dev]\""
command -v docker >/dev/null 2>&1 || die "docker not found. Install Docker Desktop and start it."
docker info >/dev/null 2>&1 || die "docker daemon not reachable. Start Docker and retry."
command -v vhs >/dev/null 2>&1 || die "vhs not found. Install: https://github.com/charmbracelet/vhs"
command -v ffmpeg >/dev/null 2>&1 || die "ffmpeg not found (vhs needs it to make the gif)."
if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
  die "No model credential. Set ANTHROPIC_API_KEY (prod) or CLAUDE_CODE_OAUTH_TOKEN (dev, with R2D_BACKEND=claude-cli)."
fi
echo "  ok — docker, vhs, ffmpeg, credential present (backend: $BACKEND)"

# --- build the sandbox base image (idempotent) -------------------------------
say "Building sandbox base image ($BASE_IMAGE)"
docker build -t "$BASE_IMAGE" images/base/

# --- run readme2demo on itself ----------------------------------------------
# docs/step-by-step.md is auto-discovered and treated as the authoritative
# guide, so the video shows install -> 163 tests -> CLI -> a verified run.
say "Running readme2demo on $SELF_URL"
readme2demo run "$SELF_URL" --llm-backend "$BACKEND"

# --- locate the run dir it just produced ------------------------------------
RUN_DIR="$(ls -1dt runs/readme2demo-*/ 2>/dev/null | head -1 || true)"
[ -n "$RUN_DIR" ] && [ -d "$RUN_DIR" ] || die "Could not find the run dir under runs/readme2demo-*. Check the output above."
RUN_DIR="${RUN_DIR%/}"
say "Run dir: $RUN_DIR"
readme2demo report "$RUN_DIR" || true

VERIFIED="$(python3 -c "import json;print(json.load(open('$RUN_DIR/manifest.json')).get('verified'))" 2>/dev/null || echo "None")"
if [ "$VERIFIED" != "True" ]; then
  echo
  echo "  ⚠ This run is not verified — see $RUN_DIR/verify.log."
  echo "    Not wiring unverified output into the repo. Fix the cause, then:"
  echo "      readme2demo resume $RUN_DIR"
  exit 1
fi

# --- wire outputs into the repo ---------------------------------------------
say "Publishing verified outputs into the repo"
DEST="examples/readme2demo"
mkdir -p "$DEST" docs
for f in tutorial.md step_by_step.md troubleshooting.md commands.sh howto.jsonld manifest.json demo.gif; do
  [ -f "$RUN_DIR/$f" ] && cp "$RUN_DIR/$f" "$DEST/$f" && echo "  examples/readme2demo/$f"
done
cp "$RUN_DIR/demo.gif" docs/demo.gif && echo "  docs/demo.gif  (README hero)"

# --- rewrite the README hero block ------------------------------------------
say "Embedding the demo in README.md"
python3 - "$RUN_DIR/manifest.json" <<'PY'
import json, re, sys, datetime
mani = json.load(open(sys.argv[1]))
commit = (mani.get("commit_sha") or "")[:7]
image  = mani.get("base_image", "readme2demo/base:latest")
date   = (mani.get("created_at") or datetime.date.today().isoformat())[:10]
block = (
    "<!-- HERO:START -->\n"
    "![readme2demo running on its own repo — verified demo](docs/demo.gif)\n\n"
    f"> ✅ Verified on {date} · image `{image}` · commit `{commit}` — "
    "generated by readme2demo running on itself.\n"
    "<!-- HERO:END -->"
)
readme = open("README.md").read()
new = re.sub(r"<!-- HERO:START.*?HERO:END -->", block, readme, count=1, flags=re.S)
open("README.md", "w").write(new)
print("  README hero updated.")
PY

say "Done"
cat <<EOF

Next:
  git add README.md docs/demo.gif examples/readme2demo
  git commit -m "docs: recursive self-demo — verified video + tutorial from our own README"
  git push

Full-resolution video (not committed to keep the repo lean):
  $RUN_DIR/demo.mp4
EOF
